[package]
name = "audible_split"
version = "0.1.0"
authors = ["Lukas Knuth <mr.luke.187@googlemail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1"
clap = "2.33.0"
rayon = "1.1.0"