name: Build & Test Release
on:
  push:
  - master # Only build (and deploy) releases from master branch!
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: cargo test
    - name: Build
      run: cargo build --release --verbose